version: '3.8'

services:
  gateway:
    build:
      context: .
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:9500"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SERVICE_ADDRESS_BASE_URL=${SERVICE_ADDRESS_BASE_URL}
      - BANDROOM_SERVICE_URL=${BANDROOM_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - IMAGE_SERVICE_URL=${IMAGE_SERVICE_URL}
      - TIME_MANAGER_SERVICE_URL=${TIME_MANAGER_SERVICE_URL}
      - PRODUCT_BANDROOM_SERVICE_URL=${PRODUCT_BANDROOM_SERVICE_URL}
      - BANDROOM_DB_USERNAME=${BANDROOM_DB_USERNAME}
      - BANDROOM_DB_PASSWORD=${BANDROOM_DB_PASSWORD}

