jwt:
  secret_key: MY-123123

service:
  address:
    base-url: http://localhost:9201
  bandroom:
    base-url: http://localhost:9300
  image:
    base-url: http://localhost:9200
  time-manager:
    base-url: http://localhost:9202





server:

  port: 9500
